//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Tizen.NUI.Xaml.XamlResourceIdAttribute("", "", typeof(global::Tizen.NUI.Examples.DataTriggerDemoPage))]

namespace Tizen.NUI.Examples {
    
    
    [global::Tizen.NUI.Xaml.XamlFilePathAttribute("H:\\NUI\\demo\\DemoUseSplitTizenNUI\\res\\layout\\1920x1080\\DataTriggerDemoPage.xaml")]
    public partial class DataTriggerDemoPage : global::Tizen.NUI.Xaml.ContentPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Tizen.NUI.Xaml.Build.Tasks.XamlG", "1.0.0.0")]
        private global::Tizen.NUI.Xaml.Forms.BaseComponents.TextLabel Label;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Tizen.NUI.Xaml.Build.Tasks.XamlG", "1.0.0.0")]
        private global::Tizen.NUI.Xaml.UIComponents.PushButton Click;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Tizen.NUI.Xaml.Build.Tasks.XamlG", "1.0.0.0")]
        private void InitializeComponent() {
            global::Tizen.NUI.Xaml.Extensions.LoadFromXaml(this, typeof(DataTriggerDemoPage));
            Label = global::Tizen.NUI.Binding.NameScopeExtensions.FindByName<global::Tizen.NUI.Xaml.Forms.BaseComponents.TextLabel>(this, "Label");
            Click = global::Tizen.NUI.Binding.NameScopeExtensions.FindByName<global::Tizen.NUI.Xaml.UIComponents.PushButton>(this, "Click");
        }
    }
}
